---
language: bash
dist: xenial

env:
  global:
    - TF_VAR_algo_name=algo TF_VAR_region=nil
    - TF_VAR_google_credentials=/dev/null GOOGLE_CREDENTIALS=/dev/null
    - DIGITALOCEAN_TOKEN=nil
    - AWS_ACCESS_KEY_ID=nil AWS_SECRET_ACCESS_KEY=nil
    - ARM_CLIENT_SECRET=nil ARM_TENANT_ID=nil ARM_CLIENT_ID=nil ARM_SUBSCRIPTION_ID=nil
    - HCLOUD_TOKEN=nil
    - SCW_TOKEN=nil SCALEWAY_ORGANIZATION=nil

matrix:
  fast_finish: true

script:
  - set -ex
  - wget https://releases.hashicorp.com/terraform/0.12.6/terraform_0.12.6_linux_amd64.zip -O terraform.zip -q && unzip terraform.zip
  - |
    for i in $(ls ./cloud); do
      export TF_VAR_algo_provider=$i
      terraform init cloud/${i}
      terraform validate cloud/${i}
    done
  - terraform fmt -write=false -list=true -diff=true -check=true -recursive

notifications:
  email: false
