#cloud-config

runcmd:
  - echo "Run additional tasks"; ${additional_tasks}
  - echo END >> /tmp/pipeline
  - touch /tmp/booted && sleep 20
  - '[ -f /var/run/reboot-required ] && shutdown -r now "Algo updates triggered" || true'
